'use strict';


module.exports = {
    UI: {
        CLOSE_MODAL: 'CLOSE_MODAL',
        KEEP_MODAL: 'KEEP_MODAL',
        FETCH_REGISTRATION: 'FETCH_REGISTRATION',
        FETCH_REGISTRATION_COMPLETE: 'FETCH_REGISTRATION_COMPLETE',
        CREATE_ALERT: 'CREATE_ALERT',
        REMOVE_ALERT: 'REMOVE_ALERT',
        FETCH_USER: 'FETCH_USER',
        FETCH_USER_COMPLETE: 'FETCH_USER_COMPLETE',
        FETCH_BANDS: 'FETCH_BANDS',
        FETCH_BANDS_COMPLETE: 'FETCH_BANDS_COMPLETE',
        FETCH_VENUES: 'FETCH_VENUES',
        FETCH_VENUES_COMPLETE: 'FETCH_VENUES_COMPLETE',
    },
    USER: {
        SET_USER: 'SET_USER',
        CLEAR_USER: 'CLEAR_USER'
    },
    CACHE: {
        AUTH_TOKEN: 'auth-token',
        USER: 'user'
    },
    DASHBOARD: {
        FETCH_DASHBOARD: 'FETCH_DASHBOARD',
        FETCH_DASHBOARD_COMPLETE: 'FETCH_DASHBOARD_COMPLETE'
    },
    BANDS: {
        SET_BANDS: 'SET_BANDS'
    },
    VENUES: {
        SET_VENUES: 'SET_VENUES'
    },
    PROFILE: {
        SET_BAND: 'SET_BAND'
    }
};
