'use strict';


module.exports = {
    UI: {
        CLOSE_MODAL: 'CLOSE_MODAL',
        KEEP_MODAL: 'KEEP_MODAL',
        FETCH_REGISTRATION: 'FETCH_REGISTRATION',
        FETCH_REGISTRATION_COMPLETE: 'FETCH_REGISTRATION_COMPLETE',
        CREATE_ALERT: 'CREATE_ALERT',
        REMOVE_ALERT: 'REMOVE_ALERT',
        FETCH_USER: 'FETCH_USER',
        FETCH_USER_COMPLETE: 'FETCH_USER_COMPLETE',
        FETCH_BANDS: 'FETCH_BANDS',
        FETCH_BANDS_COMPLETE: 'FETCH_BANDS_COMPLETE',
        FETCH_VENUES: 'FETCH_VENUES',
        FETCH_VENUES_COMPLETE: 'FETCH_VENUES_COMPLETE',
        FETCH_RESULTS: 'FETCH_RESULTS',
        FETCH_RESULTS_COMPLETE: 'FETCH_RESULTS_COMPLETE',
        FETCH_POST_BOOKING: 'FETCH_POST_BOOKING',
        FETCH_POST_BOOKING_COMPLETE: 'FETCH_POST_BOOKING_COMPLETE',
        FETCH_MESSAGES: 'FETCH_MESSAGES',
        FETCH_MESSAGES_COMPLETE: 'FETCH_MESSAGES_COMPLETE',
        SENDING_MESSAGE: 'SENDING_MESSAGE',
        SENDING_MESSAGE_COMPLETE: 'SENDING_MESSAGE_COMPLETE'
    },
    USER: {
        SET_USER: 'SET_USER',
        CLEAR_USER: 'CLEAR_USER'
    },
    CACHE: {
        AUTH_TOKEN: 'auth-token',
        USER: 'user'
    },
    DASHBOARD: {
        FETCH_DASHBOARD: 'FETCH_DASHBOARD',
        FETCH_DASHBOARD_COMPLETE: 'FETCH_DASHBOARD_COMPLETE'
    },
    BANDS: {
        SET_BANDS: 'SET_BANDS'
    },
    VENUES: {
        SET_VENUES: 'SET_VENUES'
    },
    PROFILE: {
        SET_BAND: 'SET_BAND',
        SET_VENUE: 'SET_VENUE',
        CLEAR_PROFILE: 'CLEAR_PROFILE'
    },
    SEARCH: {
        SET_RESULTS: 'SET_RESULTS',
        CLEAR_RESULTS: 'CLEAR_RESULTS',
        ADD_GENRE: 'ADD_GENRE',
        REMOVE_GENRE: 'REMOVE_GENRE',
        CLEAR_GENRES: 'CLEAR_GENRES',
        ADD_GENRE: 'ADD_GENRE',
        SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
        CLEAR_SEARCH_QUERY: 'CLEAR_SEARCH_QUERY',
        SET_ACTIVE_HOVER: 'SET_ACTIVE_HOVER',
        CLEAR_ACTIVE_HOVER: 'CLEAR_ACTIVE_HOVER'
    },
    MESSAGES: {
        ADD_MESSAGE: 'ADD_MESSAGE',
        SET_INBOXES: 'SET_INBOXES',
        SET_ACTIVE_INBOX: 'SET_ACTIVE_INBOX',
        REMOVE_ACTIVE_INBOX: 'REMOVE_ACTIVE_INBOX',
        SET_ACTIVE_MESSAGE_GROUP: 'SET_ACTIVE_MESSAGE_GROUP',
        REMOVE_ACTIVE_MESSAGE_GROUP: 'REMOVE_ACTIVE_MESSAGE_GROUP',
        IS_SENDING: 'IS_SENDING',
        IS_SENDING_COMPLETE: 'IS_SENDING_COMPLETE',
        MARK_GROUP_AS_READ: 'MARK_GROUP_AS_READ'
    },
    BOOKINGS: {
        SET_CURRENT_BOOKINGS: 'SET_CURRENT_BOOKINGS',
        CLEAR_CURRENT_BOOKINGS: 'CLEAR_CURRENT_BOOKINGS',
        SET_ACCEPTED: 'SET_ACCEPTED',
        SET_REJECTED: 'SET_REJECTED'
    }
};
